### PR TITLE
Use new input parameter construction

### LINKED ISSUE #57: Use new input parameter construction
Replace the legacy input parameter construction with the new input parameter construction.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #57

### CODE REVIEW

**Comment by loganharbour** [comment]
Ping @WilkAndy

**Comment by WilkAndy** [comment]
Oh my goodness, there are a lot of errors here.  Is this to be expected?

**Comment by loganharbour** [comment]
It is indeed not supposed to fail so horribly 😆  looking into it.

**Comment by loganharbour** [comment]
@WilkAndy looks like these failures have existed for a while https://civet.inl.gov/branch/665/

**Comment by WilkAndy** [comment]
Thank you for fixing everything, @loganharbour - you really went above-and-beyond :-)

a

**Comment by loganharbour** [comment]
Cheers! The coverage stuff failing is okay, I actually need to remove it. It's not ready to work yet

**Pull request merged**
