### PR TITLE
Fix not affine test

### PR DESCRIPTION
**Pull request by lindsayad**
In libMesh/libmesh#2997 we greatly tightened the affine map detection
tolerance. Affine map detection is mean to be an optimization only: it
should not affect results. However, previously our detection tolerance
was too loose such that we were introducing errors roughly of order 1e-6
into results for slightly deformed meshes, e.g. we would define an
element as affine when it was slightly deformed when we should have been
defining it as non-affine. With the new tightening of affine detection
we are generating results that are more accurate (albeit a bit more
slowly!)

The history got a little messy here since @loganharbour submitted his last
pull request against master somehow

### CODE REVIEW

**Comment by lindsayad** [comment]
Do we need to try redelivering a payload here or something?

**Comment by WilkAndy** [comment]
> Do we need to try redelivering a payload here or something?

Huh?  i don't understand what you mean.

**Comment by lindsayad** [comment]
If you go to repo Settings and then Webhooks can you make sure that your CIVET settings look exactly like this?
Screenshot from 2021-09-13 18-16-59
 And then make sure to select individual events and then pull requests and pushes
Screenshot from 2021-09-13 18-18-06

**Comment by WilkAndy** [comment]
Hey @lindsayad , i think i've updated the civet webhooks as you specified.

**Comment by WilkAndy** [comment]
This diff is fine, as far as i'm concerned.  Please feel free to re-gold and i can merge.

**Comment by lindsayad** [comment]
The regold is already there for `transverse3.e`. The problem is that you do not have a MOOSE submodule hash so you are testing against MOOSE master ... but we cannot get our libmesh update into MOOSE master because `ba_hun` is failing ... *but* we temporarily made `ba_hun` allowed to fail so that we could make the merge happen. So we can give MOOSE a little more time to percolate the libmesh update into master and then I will invalidate the testing here

**Comment by WilkAndy** [comment]
Aha, great, thanks @lindsayad and @loganharbour

**Comment by lindsayad** [comment]
@WilkAndy it looks like I cannot invalidate your recipe, but I'm hoping you can. We got a merge into MOOSE master so it should test green now

**Comment by lindsayad** [comment]
Hmm looks like you've got a failure for a new reason but at least your non-unit tests are passing

**Pull request merged**
