### PR TITLE
udpate error macros to use new moose functions

### LINKED ISSUE #33: update error macros with streaming to use new moose functions
PR coming...

### PR DESCRIPTION
**Pull request by rwcarlsen**
fixes #33

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hmm, @rwcarlsen , what does this PR fail?

a

**Comment by rwcarlsen** [comment]
The unit tests makefile didn't include the same modules deps as the library makefile.  Soon, we'd like to have the MOOSE makefiles set up to just have the unit tests inherit the module deps from the main project makefile.

**Comment by WilkAndy** [comment]
Thanks @rwcarlsen ,

a

**Comment by rwcarlsen** [comment]
ping - passes.

**Pull request merged**
